services:
  - type: web
    name: laravel12-react
    runtime: docker
    plan: starter
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: svc-3482219c-a389-4079-b18b-d50662524e8a-shared-dml.aws-virginia-6.svc.singlestore.com
      - key: DB_PORT
        value: 3333
      - key: DB_DATABASE
        value: db_erick_06171
      - key: DB_USERNAME
        sync: false   # pegarás el valor en el dashboard de Render
      - key: DB_PASSWORD
        sync: false   # pegarás el valor en el dashboard de Render

      # Variables extra de Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false

      # WorkOS
      - key: WORKOS_API_KEY
        sync: false
      - key: WORKOS_CLIENT_ID
        sync: false
      - key: WORKOS_WEBHOOK_SECRET
        sync: false
      - key: WORKOS_REDIRECT_URI
        sync: false
